// <auto-generated />
using System;
using Gestion2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestion2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251207215108_m3")]
    partial class m3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("Gestion2.Models.MemoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Año")
                        .HasColumnType("INTEGER");

                    b.Property<string>("De")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<int>("Folio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Para")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioRegistroId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Memos");
                });
#pragma warning restore 612, 618
        }
    }
}
